site_name: ВСË О 3D ПЕЧАТИ
site_url: https://k3d.tech
copyright: Copyright &copy; 2022-2023 Dmitry Sorkin @ K3D
theme:
  palette:
    - scheme: slate
      primary: teal
      toggle:
        icon: material/lightbulb
        name: Dark theme
    - scheme: default
      primary: teal
      toggle:
        icon: material/lightbulb-outline
        name: Light theme
  logo: assets/k3d_logo.png
  name: material
  language: ru
  favicon: pics/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
  custom_dir: overrides
plugins:
  - glightbox
  - social:
      cards_layout_options:
        background_color: "#009485"
        font_family: Handjet
  - search
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - footnotes
  - toc
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/dsorkin
    - icon: fontawesome/brands/telegram
      link: https://t.me/K_3_D
    - icon: fontawesome/brands/telegram
      link: https://t.me/vostok3dp
    - icon: material/youtube
      link: https://www.youtube.com/c/SorkinDmitry
  analytics:
    provider: custom
    property: foobar
extra_css:
  - stylesheets/extra3.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - 3D Рекомендатор:
    - Принтеры: ./part-navi/printers.md
    - Детали экструдеров: ./part-navi/extruder.md
    - Электроника: ./part-navi/electronics.md
    - Механика: ./part-navi/mechanics.md
    - Филаменты и расходники: ./part-navi/filament.md
  - VOSTOK:
    - Описание проекта: ./vostok/index.md
    - Релизы: ./vostok/releases.md
    - Инструменты: ./vostok/tools.md
    - Форум проекта: https://forum.k3d.tech
    - Инструкция по сборке:
      - С чего начать: ./vostok/guide_index.md
      - Подготовка профилей: ./vostok/profiles_preparation.md
      - Портал: ./vostok/portal.md
      - Нижняя часть рамы: ./vostok/lower_frame.md
      - Зашивка часть 1: ./vostok/enclosure_part_1.md
      - Печатающая голова LPH: ./vostok/lph_assembly.md
      - Балка оси X: ./vostok/x_beam.md
      - Натяжители: ./vostok/tensioners.md
      - Приводы осей XU: ./vostok/xu_drives.md
      - Приводы оси Y: ./vostok/y_drive.md
      - Установка ремней: ./vostok/belts.md
      - Изготовление стола: ./vostok/bed_and_heating_pad.md
      - Рама стола: ./vostok/bed_frame.md
      - Ось Z: ./vostok/z_drive.md
  - Калибровки:
      - Калибровка принтера с нуля: ./calibrations/index.md
      - Калибровка PID: ./calibrations/pid.md
      - Ручной подбор частоты Input Shaping: ./calibrations/manual_is_calibration.md
      - Тест ряби: ./calibrations/vfa.md
      - Калибровка откатов:
        - Инструкция: ./calibrations/retractions/index.md
        - Калибровщик: ./calibrations/retractions/rct.html
      - Калибровка Linear Advance:
        - Инструкция: ./calibrations/la/index.md
        - Калибровщик: ./calibrations/la/k3d_la.html
      - Калибровка точности:
        - Инструкция:  ./calibrations/accuracy/index.md
        - Релизы: ./calibrations/accuracy/releases.md
  - Другие проекты:
    - Feeder965:
      - Описание проекта: ./feeder965/index.md
      - Инструкция: ./feeder965/feeder965_assembly.md
      - Релизы: ./feeder965/releases.md
    - Minifeeder:
      - Описание проекта: ./minifeeder/index.md
      - Релизы: ./minifeeder/releases.md
      - Инструкция по сборке: ./minifeeder/minifeeder_assembly.md
    - BeMeGe: ./bemege/index.md
    - Ender-3 BMG Printhead:
      - Описание проекта: ./ebp/index.md
      - Релизы: ./ebp/releases.md
      - Инструкции по сборке:
        - Шаг 1. Покупка деталей: ./ebp/bom.md
        - Шаг 2. Печать деталей: ./ebp/printed_parts.md
        - Шаг 3. Сборка: ./ebp/assembly.md
    - Ender-3 H2 Printhead: ./ehp/index.md
    - Ender-3 Sprite Printhead:
      - Описание проекта: ./esp/index.md
      - Релизы: ./esp/releases.md
      - Инструкция для Ender-3 S1/S1 Pro/S1 Plus: ./esp/guide_s1.md
      - Инструкция для Ender-3: ./esp/guide_ender3.md
  - YouTube: http://www.youtube.com/@SorkinDmitry/
  - Telegram: http://t.me/dsorkin
  - Чат K3D: http://t.me/K_3_D
