site_name: K3D - всё о 3D печати
site_url: http://k3d.tech
copyright: Copyright &copy; 2022 Dmitry Sorkin @ K3D
theme:
  name: material
  language: ru
  logo: pics/logo.png
  favicon: pics/favicon.ico
  features:
    - navigation.tabs
    - navigation.expand
    # - navigation.sections
    # - content.tabs.link
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  custom_dir: overrides
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - footnotes
  - toc
  - pymdownx.tabbed:
      alternate_style: true
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/dsorkin
    - icon: fontawesome/brands/telegram
      link: https://t.me/K_3_D
    - icon: fontawesome/brands/telegram
      link: https://t.me/vostok3dp
    - icon: material/youtube
      link: https://www.youtube.com/c/SorkinDmitry
  analytics:
    provider: custom
    property: foobar
extra_css:
  - stylesheets/extra.css
nav:
  - Домашняя страница:
      - Домашняя страница: index.md
      - Канал Dmitry Sorkin: http://t.me/dsorkin
      - Чат K3D - Всё о 3D печати: http://t.me/K_3_D
      - Новости принтера VOSTOK: http://t.me/vostok3dp
      - Обсуждение принтера VOSTOK: http://t.me/k3d_vostok
  - Калибровки:
      - Калибровка откатов:
        - Инструкция: ./calibrations/retractions/index.md
        - Калибровщик: ./calibrations/retractions/rct.html
      - Калибровка Linear Advance:
        - Инструкция: ./calibrations/la/index.md
        - Калибровщик: ./calibrations/la/k3d_la.html
      - Ручной подбор частоты Input Shaping: ./calibrations/manual_is_calibration.md
  - VOSTOK:
    - Описание проекта: ./vostok/index.md
    - Релизы: ./vostok/releases.md
    - Сборка механики:
      - С чего начать: ./vostok/guide_index.md
      - Шаг 1 - Подготовка профилей: ./vostok/profiles_preparation.md
      - Шаг 2 - Портал: ./vostok/portal.md
      - Шаг 3 - Нижняя часть рамы: ./vostok/lower_frame.md
      - Шаг 4 - Зашивка часть 1: ./vostok/enclosure_part_1.md
      - Шаг 5 - Печатающая голова LPH: ./vostok/lph_assembly.md
      - Шаг 6 - Балка оси X: ./vostok/x_beam.md
      - Шаг 7 - Натяжители: ./vostok/tensioners.md
      - Шаг 8 - Приводы осей XU: ./vostok/xu_drives.md
      - Шаг 9 - Приводы оси Y: ./vostok/y_drive.md
      - Шаг 10 - Приводы оси Z: ./vostok/z_drive.md
      - Шаг 11 - Рама стола: ./vostok/heatbed_frame.md
      - Шаг 12 - Держатели катушек: ./vostok/spool_holders.md
      - Шаг 13 - Электроника: ./vostok/electronics.md
      - Шаг 14 - Зашивка часть 2: ./vostok/enclosure_part_2.md
    - Дополнения:
      - Инструменты: ./vostok/tools.md
  - Minifeeder:
    - Описание проекта: ./minifeeder/index.md
    - Релизы: ./minifeeder/releases.md
    - Инструкция по сборке: ./minifeeder/minifeeder_assembly.md
  - Апгрейды для Ender-3:
    - Домашняя страница раздела: ./ender_upgrades.md
    - Ender-3 BMG Printhead:
      - Описание проекта: ./ebp/index.md
      - Релизы: ./ebp/releases.md
      - Инструкции по сборке:
        - Шаг 1. Покупка деталей: ./ebp/bom.md
        - Шаг 2. Печать деталей: ./ebp/printed_parts.md
        - Шаг 3. Сборка: ./ebp/assembly.md
    - Ender-3 H2 Printhead:
      - Описание проекта: ./ehp/index.md
      - Релизы: ./ehp/releases.md
      - Инструкция: ./ehp/guide.md
    - Ender-3 Sprite Printhead:
      - Описание проекта: ./esp/index.md
      - Релизы: ./esp/releases.md
      - Инструкция для Ender-3 S1/S1 Pro/S1 Plus: ./esp/guide_s1.md
      - Инструкция для Ender-3: ./esp/guide_ender3.md